### ISSUE TITLE
Support for different S for each row of data

### ISSUE THREAD

**Issue by gaow** [stephenslab/udr#1]
It would be useful if we can provide an interface to support input of effect size `bhat` and their standard error `sbhat`. When effect size is estimated from scaled data then `sbhat` should be the same for all effects and should be easily implemented (an interface problem not an algorithm problem). It can be more challenging when `sbhat` is different for different effects, but the first case would be useful enough to at least getting the correct scale of those mixture matrices.

**Comment by pcarbo** [comment]
@gaow For the first case, when the standard error (sbhat) is the same for all effects, isn't this already handled with `mvebnm(X = bhat, S = sbhat, ...)`? What needs to be done differently? The second case is non-trivial, and potentially challenging, so we may or may not want to handle it.

**Comment by gaow** [comment]
@pcarbo I am talking about an "interface" issue where we provide the summary statistics and additionally residual correlation, similar to `mashr` input. But on a second thought this is more appropriately done in `mashr` package that calls `mvebnm`. I still had `mashr` applications in mind but I think `mvebnm` is meant to be a lot more generic than that.

> The second case is non-trivial, and potentially challenging, so we may or may not want to handle it.

Maybe let's use this ticket to discuss and document?

**Comment by pcarbo** [comment]
I think it is too early for this sort of discussion; there are more basic questions at this point about what direction to take the project.

**Comment by gaow** [comment]
Sure. I changed the title of the ticket. I think in mash (and similar) context the urgency of the feature depends a lot on how we obtain the summary statistics (such that sbhat are the same or different). I'll discuss with @stephens999 in person next time as it is also relevant to some discussion on data scaling we have in `mmbr` repo.

**Comment by pcarbo** [comment]
A quick note here: I don't see immediately how we could allow for different residual covariances S for each sample unless we think of something clever. Specifically, we are optimizing for positive definite U for the marginal covariance matrices of the form T = U + S; it isn't clear how you would extend this to optimizing U when each sample has a different S. Moreover, it seems computationally challenging to implement if a solution did exist.

**Comment by pcarbo** [comment]
As discussed, it *would* be possible to implement the ED (Bovy *et al*, 2011) updates that allow for a different S for each sample (row of X).

**Comment by pcarbo** [comment]
We have partial support for this. I'm closing this for now, with the understanding that this continues to be a work-in-progress.
