### ISSUE TITLE
avoid repeated computation of Q for scaled updates

### ISSUE THREAD

**Issue by stephens999** [stephenslab/udr#11]
currently the code repeatedly computes QQ' = U 

For scaled updates we should do this just once: compute U0=QQ' and save Q 
to be passed around to avoid recomputing it

**Comment by pcarbo** [comment]
Yeah that's a good suggestion, and the existing code should be able to easily accommodate that change.

**Comment by pcarbo** [comment]
By the way this sort of thing—making improvements to computational effort—is not something we have done comprehensively, and we aren't quite ready for, but it is fine to make obvious improvements as we see them.

**Comment by yunqiyang0215** [comment]
I added Q = get_mat_Q() in the data structure of scaled object and unconstrained object. 

In scaled object, Q won't be updated each iteration. While in unconstrained object, Q is updated each iteration in data structure.  

The functions for FA now use Q as an input argument. 

I think this issue can be closed now.

**Comment by pcarbo** [comment]
Great!
